// packages/react/src/ui/link/link.tsx
import * as React from "react";
import clx from "clsx";
import Box from "../box";
import type { LinkProps } from "./link.types";

function Link(props: LinkProps) {
  const { as = "a", underline = true, rel = "noopener noreferrer" } = props;
  return (
    <Box
      fontFamily="$body"
      fontSize="$sm"
      as={as}
      backgroundColor={props.background ? "$cardBg" : undefined}
      p={props.background ? "$2" : undefined}
      borderRadius={props.background ? "$md" : undefined}
      color={props.color ? props.color : { base: "$link", hover: "$link" }}
      textDecoration={{ base: "none", hover: underline ? "underline" : "none" }}
      attributes={{
        ...props.attributes,
        href: props.href,
        target: props.target,
        rel: rel,
      }}
      className={clx(props.className)}
    >
      {props.children}
    </Box>
  );
}

export default Link;

// packages/vue/src/ui/link/link.vue
<template>
  <Box
    fontFamily="$body"
    fontSize="$sm"
    :as="as"
    :backgroundColor="background ? '$cardBg' : undefined"
    :p="background ? '$2' : undefined"
    :borderRadius="background ? '$md' : undefined"
    :color="
      color
        ? color
        : {
            base: '$link',
            hover: '$link',
          }
    "
    :textDecoration="{
      base: 'none',
      hover: underline ? 'underline' : 'none',
    }"
    :attributes="{
      ...attributes,
      href: href,
      target: target,
      rel: rel,
    }"
    :class="clx(className)"
    ><slot
  /></Box>
</template>

<script setup lang="ts">
const eventMappings = {
  onClick: "click",
  onDoubleClick: "dblclick",
  onMouseDown: "mousedown",
  onMouseUp: "mouseup",
  onMouseEnter: "mouseenter",
  onMouseLeave: "mouseleave",
  onMouseMove: "mousemove",
  onMouseOver: "mouseover",
  onMouseOut: "mouseout",
  onKeyDown: "keydown",
  onKeyUp: "keyup",
  onKeyPress: "keypress",
  onFocus: "focus",
  onBlur: "blur",
  onInput: "input",
  onChange: "change",
  onSubmit: "submit",
  onReset: "reset",
  onScroll: "scroll",
  onWheel: "wheel",
  onDragStart: "dragstart",
  onDrag: "drag",
  onDragEnd: "dragend",
  onDragEnter: "dragenter",
  onDragLeave: "dragleave",
  onDragOver: "dragover",
  onDrop: "drop",
  onTouchStart: "touchstart",
  onTouchMove: "touchmove",
  onTouchEnd: "touchend",
  onTouchCancel: "touchcancel",
};

import clx from "clsx";
import Box from "../box";
import type { LinkProps } from "./link.types";

const props = withDefaults(defineProps<LinkProps>(), {
  as: "a",
  background: undefined,
  color: undefined,
  underline: true,
  attributes: undefined,
  href: undefined,
  target: undefined,
  rel: "noopener noreferrer",
  className: undefined,
  children: undefined,
});
</script>
